### ISSUE TITLE
Don't work with utf8 fields

### ISSUE THREAD

**Issue by InformatiqueProg** [thelia-modules/DatabasesManager#1]
```
    <vendor type="mysql">
        <parameter name="Engine" value="InnoDB"/>
        <parameter name="Charset" value="utf8"/>
    </vendor>
```

Charset of vendor in shema.xml seems to be not use...

**Comment by bilhackmac** [comment]
This data are only handle by `Propel` to generate right SQL statements.  
But now, starting with `v1.4.0` (#2), you can choose your database charset.
